/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

const path = '/3dmodels/macbook-pro.glb';

export function MacbookProLegacy({ ...props }) {
	const { nodes, materials } = useGLTF(path) as any;
	return (
		<group {...props} dispose={null}>
			<mesh castShadow receiveShadow geometry={nodes.Keyboard.geometry} material={materials.Frame}>
				<mesh castShadow receiveShadow geometry={nodes.Body.geometry} material={materials.Frame} />
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Touchbar.geometry}
					material={materials.Frame}
				/>
			</mesh>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Frame.geometry}
				material={materials.Frame}
				position={[0, -0.62, 0.047]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Logo.geometry}
					material={materials.Logo}
					position={[0, 1.2, -0.106]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Screen.geometry}
					material={materials.Screen}
					position={[0, 1.2, -0.106]}
				/>
			</mesh>
		</group>
	)
}

useGLTF.preload(path);
